name: homebrew-bufferedsocket

on: [workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install BufferedSocket
      run: |
        brew install RandomPrototypes/tap-dev/bufferedsocket
        ls /usr/local/Cellar/bufferedsocket/1.1.3
